// Generated by Unloop
// BrewMaster

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_start_brew_clicked(|| {
        println!("start_brew clicked");
    });
    
    app.on_stop_brew_clicked(|| {
        println!("stop_brew clicked");
    });
    

    
    app.run()
}
